schema-version = "1.12.0"

[install]
betterleaks.pkg-path = "betterleaks"
biome.pkg-path = "biome"
bun.pkg-path = "bun"
knip.flake = "github:RogerNavelsaker/nixpkg-knip"
gh.pkg-path = "gh"
git.pkg-path = "git"
ripgrep.pkg-path = "ripgrep"
nodejs_24.pkg-path = "nodejs_24"

[vars]
NODE_ENV = "development"
