import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { dump } from "js-yaml";
import { extractHttpRoutes } from "./http-routes";

const root = resolve(import.meta.dir, "..");
const outputPath = resolve(root, "docs/openapi.yaml");

type OpenApiOperation = {
	operationId: string;
	summary: string;
	"x-senshac-kind": "api" | "page";
	"x-senshac-redirect": boolean;
	"x-pagespeed-audit": boolean;
	parameters?: Array<Record<string, unknown>>;
	responses: Record<string, { description: string }>;
};

type OpenApiPathItem = {
	get?: OpenApiOperation;
	post?: OpenApiOperation;
	put?: OpenApiOperation;
	delete?: OpenApiOperation;
	patch?: OpenApiOperation;
	"x-astro-all"?: OpenApiOperation;
};

export type OpenApiDocument = {
	openapi: "3.1.0";
	info: {
		title: string;
		version: string;
		description: string;
	};
	paths: Record<string, OpenApiPathItem>;
};

export function buildOpenApiDocument(): OpenApiDocument {
	const pkg = JSON.parse(
		readFileSync(resolve(root, "package.json"), "utf8"),
	) as {
		version: string;
	};
	const paths: Record<string, OpenApiPathItem> = {};

	for (const route of extractHttpRoutes()) {
		const parameters: Array<Record<string, unknown>> = [];
		const path = route.pattern.replace(
			/:([A-Za-z_][A-Za-z0-9_]*)/g,
			(_, name: string) => {
				parameters.push({
					name,
					in: "path",
					required: true,
					schema: { type: "string" },
				});
				return `{${name}}`;
			},
		);
		const operation = {
			operationId: route.handler,
			summary: `${route.method} ${route.pattern}`,
			"x-senshac-kind": route.kind,
			"x-senshac-redirect": route.redirect,
			"x-pagespeed-audit": route.pagespeedAudit,
			...(parameters.length > 0 ? { parameters } : {}),
			responses: { "200": { description: "Successful response." } },
		};
		paths[path] ??= {};
		const operationKey =
			route.method === "ALL"
				? "x-astro-all"
				: (route.method.toLowerCase() as keyof OpenApiPathItem);
		paths[path][operationKey] = operation;
	}

	return {
		openapi: "3.1.0",
		info: {
			title: "Senshac HTTP Routes",
			version: pkg.version,
			description: "Generated from Astro src/pages page and endpoint files.",
		},
		paths,
	};
}

export function renderOpenApi() {
	return [
		"# AUTO-GENERATED by `bun run gen:openapi` from `src/pages/`.",
		"# Do not edit by hand. CI fails if this file is out of sync.",
		"",
		dump(buildOpenApiDocument(), { lineWidth: 100, noRefs: true }),
	].join("\n");
}

function main() {
	const content = renderOpenApi();
	if (process.argv.includes("--check")) {
		const existing = readFileSync(outputPath, "utf8");
		if (existing !== content) {
			console.error("docs/openapi.yaml is stale. Run `bun run gen:openapi`.");
			process.exit(1);
		}
		return;
	}
	writeFileSync(outputPath, content);
}

if (import.meta.main) main();
