import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { extractHttpRoutes } from "./http-routes";

const outputPath = resolve(import.meta.dir, "../docs/http-api.md");

export function renderHttpApiDocs() {
	const routes = extractHttpRoutes();
	const lines = [
		"# Senshac HTTP Routes",
		"",
		"<!-- AUTO-GENERATED by `bun run gen:docs` from Astro `src/pages/`. -->",
		"<!-- Do not edit by hand. CI fails if this file is out of sync. -->",
		"",
		"PageSpeed routes are explicitly opted in from their Astro source files.",
		"",
		`Total routes: **${routes.length}**.`,
		"",
		"| Method | Pattern | Handler | Kind | Redirect | PageSpeed |",
		"| --- | --- | --- | --- | --- | --- |",
	];

	for (const route of routes) {
		lines.push(
			`| \`${route.method}\` | \`${route.pattern}\` | \`${route.handler}\` | ${route.kind} | ${route.redirect ? "yes" : "no"} | ${route.pagespeedAudit ? "yes" : "no"} |`,
		);
	}

	return `${lines.join("\n")}\n`;
}

function main() {
	const content = renderHttpApiDocs();
	if (process.argv.includes("--check")) {
		const existing = readFileSync(outputPath, "utf8");
		if (existing !== content) {
			console.error("docs/http-api.md is stale. Run `bun run gen:docs`.");
			process.exit(1);
		}
		return;
	}
	writeFileSync(outputPath, content);
}

if (import.meta.main) main();
